[package]
name = "morse"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
morse-codec = "0.4.11"

[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
